app/blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from core.views import (
    IndexView, PostsView,
    PostDetailView, AboutView,
    ProfileView, PostListView,
    PostAddView, PostEditView,
    PostDeleteView, NewsletterView,
    NewsletterDeleteView, AdminView,
    SetupView, add_newsletter
    )

urlpatterns = [
    #path('admin/', admin.site.urls),

    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('artigos/', PostsView.as_view(), name="posts"),
    path('artigo/<int:pk>/', PostDetailView.as_view(), name="post_detail"),
    path('sobre-mim/', AboutView.as_view(), name="about"),
    path('setup/', SetupView.as_view(), name="setup"),

    path('inscrever/', add_newsletter, name="newsletter"),

    path('admin/', AdminView.as_view(), name="admin"),
    path('admin/perfil/', ProfileView.as_view(), name="admin_perfil"),

    path('admin/newsletter/', NewsletterView.as_view(), name="admin_newsletter"),
    path('admin/newsletter/deletar/<int:pk>/', NewsletterDeleteView.as_view(), name="admin_newsletter_remove"),

    path('admin/posts/', PostListView.as_view(), name="admin_posts"),
    path('admin/posts/adicionar/', PostAddView.as_view(), name="admin_posts_add"),
    path('admin/posts/editar/<int:pk>/', PostEditView.as_view(), name="admin_posts_edit"),
    path('admin/posts/deletar/<int:pk>/', PostDeleteView.as_view(), name="admin_posts_remove"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Profile(models.Model):
    """
    Modelo que representa um perfil de usuário.
    
    Campos:
        - name (CharField): O nome do perfil.
        - profile_picture (ImageField): A foto de perfil do usuário.
        - about_me (TextField): Uma descrição sobre o usuário.
        - linkedin (URLField): A URL do perfil do usuário no LinkedIn.
        - github (URLField): A URL do perfil do usuário no GitHub.
        - instagram (URLField): A URL do perfil do usuário no Instagram.
        - twitter (URLField): A URL do perfil do usuário no Twitter.
        - blog_name (CharField): O nome do blog do usuário.
        - blog_description (TextField): Uma descrição do blog do usuário.
        - blog_theme (CharField): a cor do tema do blog.
    """
    THEME_CHOICES = [
        ('#ff5e3a', 'Laranja'),
        ('#4caf50', 'Verde'),
        ('#9c27b0', 'Roxo'),
        ('#ff9800', 'Amarelo'),
        ('#2196f3', 'Azul'),
        ('#e91e63', 'Rosa'),
        ('#00bcd4', 'Ciano'),
        ('#8bc34a', 'Verde Claro'),
        ('#ffc107', 'Amarelo Escuro'),
        ('#3f51b5', 'Azul Escuro'),
    ]
    name = models.CharField(max_length=100)
    profile_picture = models.ImageField(upload_to='profile/')
    about_me = models.TextField()
    linkedin = models.URLField(blank=True)
    github = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    blog_name = models.CharField(max_length=100)
    blog_description = models.TextField()
    blog_theme = models.CharField(max_length=10, choices=THEME_CHOICES)
    
    def __str__(self):
        return self.name
    
   
class Newsletter(models.Model):
    """
    Modelo que representa uma inscrição em uma newsletter.
    
    Campos:
        - email (EmailField): O endereço de e-mail da inscrição.
        - subscribed_at (DateTimeField): A data e hora em que a inscrição foi feita.
    """
    email = models.EmailField()
    subscribed_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email


class Post(models.Model):
    """
    Representa um post no blog.

    Campos:
        - title (str): O título do post.
        - banner (ImageField): O banner do post.
        - description (str): A descrição do post.
        - content (RichTextField): O conteúdo completo do post.
        - created (DateTimeField): A data e hora de criação do post.
    """
    title = models.CharField(max_length=200)
    banner = models.ImageField(upload_to='posts', null=True, blank=True)
    description = models.TextField()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

app/core/forms.py
from django import forms

from core.models import Profile, Post, Newsletter


class ProfileForm(forms.ModelForm):
    """
    Formulário para criação ou edição de perfil.

    Este formulário é usado para editar os campos do perfil do usuário.
    Ele adiciona automaticamente a classe 'form-control' a todos os campos,
    garantindo que sejam estilizados corretamente pelo Bootstrap.

    Args:
        *args: Argumentos posicionais adicionais a serem passados para a classe pai.
        **kwargs: Argumentos de palavras-chave adicionais a serem passados para a classe pai.

    Atributos:
        Meta: Classe aninhada que define as meta-informações do formulário.
        - model: Classe Profile
        - fields: Todos os campos do modelo Profile
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields[field_name]
            if 'class' in field.widget.attrs:
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Profile
        fields = '__all__'


class PostForm(forms.ModelForm):
    """
    Formulário para criação ou edição de perfil.

    Este formulário é usado para criar e editar publicações da aplicação.
    Ele adiciona automaticamente a classe 'form-control' a todos os campos,
    garantindo que sejam estilizados corretamente pelo Bootstrap.

    Args:
        *args: Argumentos posicionais adicionais a serem passados para a classe pai.
        **kwargs: Argumentos de palavras-chave adicionais a serem passados para a classe pai.

    Atributos:
        Meta: Classe aninhada que define as meta-informações do formulário.
        - model: Classe Post
        - fields: Todos os campos do modelo Post
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields[field_name]
            if 'class' in field.widget.attrs:
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = '__all__'


class NewsletterForm(forms.ModelForm):
    """
    Formulário para adicionar novas inscrições.


    Args:
        *args: Argumentos posicionais adicionais a serem passados para a classe pai.
        **kwargs: Argumentos de palavras-chave adicionais a serem passados para a classe pai.

    Atributos:
        Meta: Classe aninhada que define as meta-informações do formulário.
        - model: Classe Newsletter
        - fields: Todos os campos do modelo Newsletter
    """
    class Meta:
        model = Newsletter
        fields = '__all__'

app/core/views.py
from django.views.generic import (
    TemplateView, ListView, 
    FormView, CreateView, 
    UpdateView, DeleteView,
    DetailView,
)
from django.urls import reverse_lazy
from django.shortcuts import redirect, render

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models.functions import TruncMonth
from django.db.models import Count

from core.forms import ProfileForm, PostForm, NewsletterForm
from core.models import Profile, Post, Newsletter


class IndexView(ListView):
    """
    Classe IndexView
    ----------------
    Classe responsável por exibir a página inicial (index) da aplicação.
    Herda da classe ListView do Django para renderizar um template simples.
    Por padrão, o template esperado é "index.html".
    
    Atributos:
        - template_name: nome do template a ser renderizado (padrão: "index.html")
        - model: nome do modelo que vai ser listado
        - context_object_name: nome que será enviado para o template contendo os posts
        - paginate_by: quantidade de posts para serem exibidos por página
    Métodos:
        - get_context_data(): retorna o contexto de dados para ser usado no template
    """
    template_name = "pages/index.html"
    model = Post
    context_object_name = "posts"
    paginate_by = 4
    
    def get(self, request, *args, **kwargs):
        if Profile.objects.filter(pk=1).exists():
            return super().get(request, *args, **kwargs)
        return redirect("/setup")

    def get_context_data(self, **kwargs):
        profile = Profile.objects.get(pk=1)
        context = super().get_context_data(**kwargs)
        context["title"] = "Página Inicial"
        context["menu"] = "index"
        context["profile"] = profile
        return context
    

class PostsView(ListView):
    template_name = "pages/articles.html"
    model = Post
    ordering = "created"
    context_object_name = "posts"
    paginate_by = 9
    
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.reverse()
    
    def get_context_data(self, **kwargs):
        profile = Profile.objects.get(pk=1)
        context = super().get_context_data(**kwargs)
        context["title"] = "Artigos"
        context["menu"] = "posts"
        context["profile"] = profile
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "pages/post.html"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        profile = Profile.objects.get(pk=1)
        context = super().get_context_data(**kwargs)
        context["title"] = context["post"].title
        context["profile"] = profile
        return context


class AboutView(TemplateView):
    template_name = "pages/about.html"
    
    def get_context_data(self, **kwargs):
        profile = Profile.objects.get(pk=1)
        context = super().get_context_data(**kwargs)
        context["title"] = "Sobre"
        context["profile"] = profile
        context["menu"] = "about"
        return context


# Admin
class ProfileView(LoginRequiredMixin, FormView):
    form_class = ProfileForm
    login_url = "/"
    template_name = "pages/admin/profile.html"
    success_url = "/admin/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "profile"
        context["profile"] = Profile.objects.get(id=1)
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        profile = Profile.objects.get(id=1)
        kwargs['instance'] = profile
        return kwargs
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class NewsletterView(LoginRequiredMixin, ListView):
    template_name = "pages/admin/newsletter.html"
    login_url = "/"
    model = Newsletter
    context_object_name = "emails"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "newsletter"
        context["profile"] = Profile.objects.get(id=1)
        return context
    

class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    login_url = "/"
    template_name = 'pages/admin/index.html'
    success_url = reverse_lazy('admin_newsletter')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "newsletter"
        context["profile"] = Profile.objects.get(id=1)
        return context


class PostListView(LoginRequiredMixin, ListView):
    template_name = "pages/admin/posts-list.html"
    login_url = "/"
    model = Post
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "posts"
        context["profile"] = Profile.objects.get(id=1)
        return context


class PostAddView(LoginRequiredMixin, CreateView):
    template_name = "pages/admin/posts-form.html"
    login_url = "/"
    form_class = PostForm
    model = Post
    success_url = reverse_lazy("admin_posts")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "posts"
        context["profile"] = Profile.objects.get(id=1)
        return context
    

class PostEditView(LoginRequiredMixin, UpdateView):
    template_name = "pages/admin/posts-form.html"
    login_url = "/"
    form_class = PostForm
    model = Post
    success_url = reverse_lazy("admin_posts")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "posts"
        context["profile"] = Profile.objects.get(id=1)
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    login_url = "/"
    template_name = 'pages/admin/index.html'
    success_url = reverse_lazy('admin_posts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = "posts"
        context["profile"] = Profile.objects.get(id=1)
        return context


class AdminView(LoginRequiredMixin, TemplateView):
    template_name = "pages/admin/index.html"
    login_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Dados de publicações
        posts = Post.objects.annotate(month=TruncMonth('created')).values(
            'month').annotate(count=Count('id')).order_by('month')
        labels = [post['month'].strftime('%B %Y') for post in posts]
        data = [post['count'] for post in posts]

        # Dados de Inscrições
        subscribes = Newsletter.objects.annotate(month=TruncMonth('subscribed_at')).values(
            'month').annotate(count=Count('id')).order_by('month')
        sublabels = [subs['month'].strftime('%B %Y') for subs in subscribes]
        subdata = [subs['count'] for subs in posts]

        context["subtotal"] = Newsletter.objects.count()
        context["posttotal"] = Post.objects.count()
        context["labelschart"] = labels
        context["datachart"] = data
        context["sublabels"] = sublabels
        context["subdata"] = subdata
        context["menu"] = "home"
        context["profile"] = Profile.objects.get(id=1)
        return context
    

# Setup
class SetupView(TemplateView):
    """
    Classe SetupView
    ----------------
    Classe responsável por exibir a página de setup da aplicação.
    Herda da classe TemplateView do Django para renderizar um template simples.
    Por padrão, o template esperado é "setup.html".
    
    Atributos:
        - template_name: nome do template a ser renderizado (padrão: "setup.html")
    Métodos:
        - get(): recebe e retorna os dados requisição do tipo GET
        - post(): recebe a requisição POST e realiza as operações de setup.
        - get_context_data(): retorna o contexto de dados para ser usado no template
    """
    template_name = "pages/setup.html"

    def get(self, request, *args, **kwargs):
        if Profile.objects.filter(pk=1).exists():
            return redirect("/")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        profileform = ProfileForm(request.POST or None, request.FILES or None)
        userform = UserCreationForm({
            "username": request.POST["username"],
            "password1": request.POST["password1"],
            "password2": request.POST["password1"],
        })
        if all([profileform.is_valid(), userform.is_valid()]):
            profileform.save()
            userform.save()
            username = userform.cleaned_data.get('username')
            password = userform.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("/")
        else:
            errors = []
            errors.append(profileform.errors)
            errors.append(userform.errors)
        return render(request, self.template_name, 
                      {'userform': userform, 'profileform': profileform, 'errors': errors})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profileform'] = ProfileForm()
        context['postform'] = PostForm()
        return context


# Newsletter
def add_newsletter(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = NewsletterForm()

    return redirect('index')

app/core/templates/pages/setup.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - Configurações Iniciais </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>

    <div class="toast-container position-fixed top-0 end-0 p-3" style="z-index: 9999;">
        {% for error in errors %}
            {% for field in error.values %}
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
                <div class="toast-header">
                    <strong class="mr-auto">Mensagem</strong>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                   {{ field }}
                </div>
            </div>
            {% endfor %}
        {% endfor %}
    </div>

    <header class="hero">
        <div class="container">
            <h1 class="hero-title">Bem-vindo, conclua o cadastro do seu Blog</h1>
            <p class="hero-description">Utilize o formulário abaixo para configurar seu blog.</p>
        </div>
    </header>

    <button id="toggle-mode" class="dark-mode-toggle" aria-label="Alternar Modo">
        <i class="fas fa-sun"></i>
        <i class="fas fa-moon"></i>
    </button>

    <div class="container mt-3 mb-5">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div id="wizard" class="wizard">
                    <div class="wizard-header mb-3">
                        <ul class="nav nav-pills d-none">
                            <li class="nav-item">
                                <a class="nav-link active" href="#step1" data-toggle="tab">Etapa 1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#step2" data-toggle="tab">Etapa 2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#step3" data-toggle="tab">Etapa 3</a>
                            </li>
                        </ul>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="step1">
                                <h3 class="mb-3">Etapa 1: Configurações do Blog</h3>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_blog_name">Nome do Blog</label>
                                    <input type="text" name="blog_name" maxlength="100" class="form-control" required=""
                                        id="id_blog_name" placeholder="Nome do blog">
                                </div>
                                <div class="form-group">
                                    <label for="id_blog_description">Descrição do Blog</label>
                                    <textarea class="form-control" id="id_blog_description" required
                                        name="blog_description" placeholder="Breve descrição do blog"
                                        rows="4"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="blog_theme">Tema do Blog</label>
                                    {{ profileform.blog_theme }}
                                </div>
                                <div class="mt-4 row">
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary next w-100">Próxima Etapa <i
                                                class="fas fa-arrow-right ml-2"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="step2">
                                <h3 class="mb-3">Etapa 2: Perfil do Criador</h3>
                                <div class="form-group">
                                    <label for="id_name">Nome do Autor</label>
                                    <input type="text" name="name" maxlength="100" placeholder="Seu nome"
                                        class="form-control" required="" id="id_name">
                                </div>
                                <div class="form-group">
                                    <label for="id_profile_picture">Foto do Autor</label>
                                    {{ profileform.profile_picture }}
                                </div>
                                <div class="form-group">
                                    <label for="id_about_me">Descrição do Autor</label>
                                    <textarea class="form-control" id="id_about_me" required name="about_me"
                                        placeholder="Fale sobre você, quais sobre seus hobbies, gostos e o que te motiva a fazer o que faz."
                                        rows="6"></textarea>
                                </div>
                                <div class="mt-4 row">
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary prev w-100"><i
                                                class="fas fa-arrow-left mr-2"></i> Etapa Anterior</button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary next w-100">Próxima Etapa <i
                                                class="fas fa-arrow-right ml-2"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="step3">
                                <h3 class="mb-3">Etapa 3: Usuário e Senha </h3>
                                <div class="form-group">
                                    <label for="id_username">Nome de Usuário</label>
                                    <input type="text" name="username" class="form-control" placeholder="gabriel"
                                        required="" id="id_username">
                                </div>
                                <div class="form-group">
                                    <label for="id_username">Senha de Acesso</label>
                                    <input type="password" name="password1" plachol class="form-control"
                                        placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;" required=""
                                        id="id_password1">
                                </div>
                                <!--
                                <h3 class="mb-3">Etapa 3: Meu Primeiro Post</h3>
                                <div class="form-group">
                                    <label for="id_title">Título do Post</label>
                                    <input type="text" name="title" maxlength="200" class="form-control" placeholder="Meu Primeiro Post" required="" id="id_title">
                                </div>
                                <div class="form-group">
                                    <label for="id_title">Banner do Post</label>
                                    {{ postform.banner }}
                                </div>
                                <div class="form-group">
                                    <label for="id_description">Descrição do Post</label>
                                    <textarea class="form-control" id="id_description" required name="description"
                                    placeholder="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dapibus ex non lectus auctor, nec fermentum odio scelerisque."
                                    rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="id_title">Conteúdo do Post</label>
                                    {{ postform.media }}
                                    {{ postform.content }}
                                </div>
                                -->
                                <div class="mt-4 row">
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-primary prev w-100"><i
                                                class="fas fa-arrow-left mr-2"></i> Etapa Anterior</button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-primary w-100">Salvar
                                            Configurações</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"></script>
    <script src="/static/js/setup.js"></script>

    <script>
        $(document).ready(function () {
            $('#toggle-mode').click(function () {
                $('body, .card, .card-title, .card-text, .hero, .hero-title, .hero-description, .btn, a').toggleClass('dark-mode');
            });
        });
    </script>

    <script>
        var nextBtns = document.querySelectorAll('.next');
        var prevBtns = document.querySelectorAll('.prev');
        var tabs = document.querySelectorAll('.tab-pane');

        nextBtns.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var currentTab = btn.closest('.tab-pane');
                var nextTab = currentTab.nextElementSibling;
                if (nextTab && validateRequiredFields(currentTab)) {
                    currentTab.classList.remove('show', 'active');
                    nextTab.classList.add('show', 'active');
                }
            });
        });

        prevBtns.forEach(function (btn) {
            btn.addEventListener('click', function (e) {
                e.preventDefault();
                var currentTab = btn.closest('.tab-pane');
                var prevTab = currentTab.previousElementSibling;
                if (prevTab) {
                    currentTab.classList.remove('show', 'active');
                    prevTab.classList.add('show', 'active');
                }
            });
        });

        function validateRequiredFields(tab) {
            var fields = tab.querySelectorAll('[required]');
            var isValid = true;

            fields.forEach(function (field) {
                if (field.value.trim() === '') {
                    isValid = false;
                    field.classList.add('is-invalid');
                } else {
                    field.classList.remove('is-invalid');
                }
            });

            return isValid;
        }
    </script>

    <script>
        $(document).ready(function () {
            $('#id_blog_theme').change(function () {
                var newColor = $(this).val();
                var previousColor = $('.btn-primary').css('background-color');
                $('body').find('*').each(function () {
                    var color = $(this).css('background-color');
                    if (color === previousColor) {
                        $(this).css('background-color', newColor);
                        $(this).css('border-color', newColor);
                    }
                });
            });
        });
        $(document).ready(function () {
            $('.toast').toast({ delay: 2000 })
            $('.toast').toast('show');
        });
    </script>

    <script>
        var options = document.querySelectorAll("option");
        for (var i = 0; i < options.length; i++) {
            if (options[i].text === "---------") {
                options[i].text = "Não Selecionado";
            }
        }
    </script>

</body>

</html>